<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\AdminCommerceController;
use App\Http\Controllers\AdminSellerController;
use App\Http\Controllers\AdminPayoutController;
use App\Http\Controllers\AdminPromotionController;
use App\Http\Controllers\AdminReviewController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\GoogleAuthController;
use App\Http\Controllers\OtpController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SellerController;
use App\Http\Controllers\SellerFinanceController;
use App\Http\Controllers\SellerPayoutController;
use App\Http\Controllers\SellerProductController;
use App\Http\Controllers\SellerOrderController;
use App\Http\Controllers\StorefrontController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\LoyaltyController;

Route::get('/health', HealthController::class)->name('health');
Route::get('/', function () { return view('landing'); })->name('landing');
Route::post('/payments/callback/mtn', [PaymentController::class, 'callbackMtn'])->name('payments.callback.mtn');
Route::post('/payments/callback/airtel', [PaymentController::class, 'callbackAirtel'])->name('payments.callback.airtel');
Route::middleware('guest')->group(function () {
    Route::get('/login', fn () => view('auth.login-enhanced'))->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
    Route::get('/login/otp', [OtpController::class, 'challenge'])->name('login.otp.challenge');
    Route::post('/login/otp/request', [OtpController::class, 'requestOtp'])->name('login.otp.request');
    Route::post('/login/otp/verify', [OtpController::class, 'verify'])->name('login.otp.verify');
    Route::get('/auth/google', [GoogleAuthController::class, 'redirect'])->name('auth.google');
    Route::get('/auth/google/callback', [GoogleAuthController::class, 'callback'])->name('auth.google.callback');
    Route::get('/register', [AuthController::class, 'showRegister'])->name('register');
    Route::post('/register', [AuthController::class, 'register'])->name('register.submit');
});
Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/shop', [StorefrontController::class, 'index'])->name('storefront.index');
    Route::get('/shop/product/{product}', [StorefrontController::class, 'show'])->name('storefront.show');
    Route::post('/shop/cart/add/{product}', [StorefrontController::class, 'addToCart'])->name('storefront.cart.add');
    Route::get('/shop/cart', [StorefrontController::class, 'cart'])->name('storefront.cart');
    Route::post('/shop/cart', [StorefrontController::class, 'updateCart'])->name('storefront.cart.update');
    Route::delete('/shop/cart/{product}', [StorefrontController::class, 'removeFromCart'])->name('storefront.cart.remove');
    Route::get('/wishlist', [WishlistController::class, 'index'])->name('wishlist.index');
    Route::post('/wishlist/{product}/toggle', [WishlistController::class, 'toggle'])->name('wishlist.toggle');
    Route::post('/products/{product}/reviews', [ReviewController::class, 'store'])->name('reviews.store');
    Route::get('/loyalty', [LoyaltyController::class, 'index'])->name('loyalty.index');
    Route::post('/promotions/validate', [PromotionController::class, 'validateCode'])->name('promotions.validate');
    Route::get('/checkout', [CheckoutController::class, 'create'])->name('checkout');
    Route::post('/checkout', [CheckoutController::class, 'store'])->name('checkout.store');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show');
    Route::get('/orders/{order}/pay', [PaymentController::class, 'create'])->name('payments.create');
    Route::post('/orders/{order}/pay', [PaymentController::class, 'store'])->name('payments.store');
    Route::get('/orders/{order}/payments/{payment}', [PaymentController::class, 'show'])->name('payments.show');
    Route::get('/sell', [SellerController::class, 'apply'])->name('seller.apply');
    Route::post('/sell', [SellerController::class, 'store'])->name('seller.apply.store');
    Route::get('/seller/dashboard', [SellerController::class, 'dashboard'])->name('seller.dashboard');
    Route::get('/seller/finance', [SellerFinanceController::class, 'index'])->name('seller.finance.index');
    Route::get('/seller/payouts', [SellerPayoutController::class, 'index'])->name('seller.payouts.index');
    Route::post('/seller/payouts', [SellerPayoutController::class, 'store'])->name('seller.payouts.store');
    Route::get('/seller/products', [SellerProductController::class, 'index'])->name('seller.products.index');
    Route::get('/seller/products/create', [SellerProductController::class, 'create'])->name('seller.products.create');
    Route::post('/seller/products', [SellerProductController::class, 'store'])->name('seller.products.store');
    Route::get('/seller/products/{product}/edit', [SellerProductController::class, 'edit'])->name('seller.products.edit');
    Route::put('/seller/products/{product}', [SellerProductController::class, 'update'])->name('seller.products.update');
    Route::delete('/seller/products/{product}', [SellerProductController::class, 'destroy'])->name('seller.products.destroy');
    Route::get('/seller/orders', [SellerOrderController::class, 'index'])->name('seller.orders.index');
    Route::get('/seller/orders/{order}', [SellerOrderController::class, 'show'])->name('seller.orders.show');
    Route::patch('/seller/orders/{order}/status', [SellerOrderController::class, 'updateStatus'])->name('seller.orders.status');
    Route::get('/admin/commerce', [AdminCommerceController::class, 'index'])->name('admin.commerce');
    Route::get('/admin/promotions', [AdminPromotionController::class, 'index'])->name('admin.promotions.index');
    Route::post('/admin/promotions', [AdminPromotionController::class, 'store'])->name('admin.promotions.store');
    Route::patch('/admin/promotions/{promotion}/toggle', [AdminPromotionController::class, 'toggle'])->name('admin.promotions.toggle');
    Route::get('/admin/reviews', [AdminReviewController::class, 'index'])->name('admin.reviews.index');
    Route::patch('/admin/reviews/{review}', [AdminReviewController::class, 'update'])->name('admin.reviews.update');
    Route::get('/admin/sellers', [AdminSellerController::class, 'index'])->name('admin.sellers.index');
    Route::patch('/admin/sellers/{sellerProfile}/approve', [AdminSellerController::class, 'approve'])->name('admin.sellers.approve');
    Route::patch('/admin/sellers/{sellerProfile}/reject', [AdminSellerController::class, 'reject'])->name('admin.sellers.reject');
    Route::get('/admin/payouts', [AdminPayoutController::class, 'index'])->name('admin.payouts.index');
    Route::patch('/admin/payouts/{payout}/approve', [AdminPayoutController::class, 'approve'])->name('admin.payouts.approve');
    Route::patch('/admin/payouts/{payout}/paid', [AdminPayoutController::class, 'paid'])->name('admin.payouts.paid');
    Route::patch('/admin/payouts/{payout}/fail', [AdminPayoutController::class, 'fail'])->name('admin.payouts.fail');
    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/analytics', [ProductController::class, 'analytics'])->name('products.analytics');
    Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::put('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');
    Route::get('/products/{product}/stock-in', [ProductController::class, 'stockIn'])->name('products.stockIn');
    Route::post('/products/{product}/stock-in', [ProductController::class, 'processStockIn'])->name('products.stockIn.submit');
    Route::get('/products/{product}/stock-out', [ProductController::class, 'stockOut'])->name('products.stockOut');
    Route::post('/products/{product}/stock-out', [ProductController::class, 'processStockOut'])->name('products.stockOut.submit');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
});
